// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingRecordsApp.Migrations
{
    [DbContext(typeof(BuildingContext))]
    [Migration("20250513162957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId");

                    b.HasIndex("AgentCompanyId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AgentCompany", b =>
                {
                    b.Property<int>("AgentCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentCompanyId");

                    b.ToTable("AgentCompanies");
                });

            modelBuilder.Entity("Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfUnits")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("CompanyTrust", b =>
                {
                    b.Property<int>("CompanyTrustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyTrustId");

                    b.ToTable("CompanyTrusts");
                });

            modelBuilder.Entity("Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowedPets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonsOccupying")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignedRules")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaseId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("Occupancy", b =>
                {
                    b.Property<int>("OccupancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccupationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("OccupancyId");

                    b.HasIndex("UnitId");

                    b.ToTable("Occupancies");
                });

            modelBuilder.Entity("Ownership", b =>
                {
                    b.Property<int>("OwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyTrustId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnershipId");

                    b.HasIndex("CompanyTrustId");

                    b.ToTable("Ownership");
                });

            modelBuilder.Entity("ParkingBay", b =>
                {
                    b.Property<int>("ParkingBayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkingBayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParkingBayID");

                    b.HasIndex("UnitID");

                    b.ToTable("ParkingBays");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OccupancyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("AgentCompanyId");

                    b.HasIndex("OccupancyId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("StoreRoom", b =>
                {
                    b.Property<int>("StoreRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreRoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoreRoomId");

                    b.HasIndex("UnitId");

                    b.ToTable("StoreRooms");
                });

            modelBuilder.Entity("TagRemoteRecord", b =>
                {
                    b.Property<int>("TagRemoteRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemotesAgent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemotesOccupant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemotesOwner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsAgent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsOccupant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagRemoteRecordId");

                    b.ToTable("TagRemoteRecords");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirconditioningUnits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DbInverter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Housekeeping")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnershipId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryContactPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SublettingAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagRemoteRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("UnitId");

                    b.HasIndex("AgentId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LeaseId")
                        .IsUnique();

                    b.HasIndex("OwnershipId");

                    b.HasIndex("PrimaryContactPersonId");

                    b.HasIndex("TagRemoteRecordId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Agent", b =>
                {
                    b.HasOne("AgentCompany", "AgentCompany")
                        .WithMany()
                        .HasForeignKey("AgentCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentCompany");
                });

            modelBuilder.Entity("Occupancy", b =>
                {
                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Ownership", b =>
                {
                    b.HasOne("CompanyTrust", null)
                        .WithMany("Ownerships")
                        .HasForeignKey("CompanyTrustId");
                });

            modelBuilder.Entity("ParkingBay", b =>
                {
                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.HasOne("AgentCompany", null)
                        .WithMany("Agents")
                        .HasForeignKey("AgentCompanyId");

                    b.HasOne("Occupancy", null)
                        .WithMany("Occupants")
                        .HasForeignKey("OccupancyId");
                });

            modelBuilder.Entity("StoreRoom", b =>
                {
                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.HasOne("Agent", "Agent")
                        .WithMany("Units")
                        .HasForeignKey("AgentId");

                    b.HasOne("Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lease", "Lease")
                        .WithOne("Unit")
                        .HasForeignKey("Unit", "LeaseId");

                    b.HasOne("Ownership", "Ownership")
                        .WithMany()
                        .HasForeignKey("OwnershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Person", "PrimaryContactPerson")
                        .WithMany()
                        .HasForeignKey("PrimaryContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TagRemoteRecord", "TagRemoteRecord")
                        .WithMany()
                        .HasForeignKey("TagRemoteRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Building");

                    b.Navigation("Lease");

                    b.Navigation("Ownership");

                    b.Navigation("PrimaryContactPerson");

                    b.Navigation("TagRemoteRecord");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Agent", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AgentCompany", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("Building", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("CompanyTrust", b =>
                {
                    b.Navigation("Ownerships");
                });

            modelBuilder.Entity("Lease", b =>
                {
                    b.Navigation("Unit")
                        .IsRequired();
                });

            modelBuilder.Entity("Occupancy", b =>
                {
                    b.Navigation("Occupants");
                });
#pragma warning restore 612, 618
        }
    }
}
