// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingRecordsApp.Migrations
{
    [DbContext(typeof(BuildingContext))]
    [Migration("20260815123419_EnforceRequiredRegisterRelationships")]
    partial class EnforceRequiredRegisterRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentId");

                    b.HasIndex("AgentCompanyId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.AgentCompany", b =>
                {
                    b.Property<int>("AgentCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentCompanyId");

                    b.ToTable("AgentCompanies");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfUnits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("PropertyId", "Name")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeclaredOccupantCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PetsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignedRules")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaseId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Occupancy", b =>
                {
                    b.Property<int>("OccupancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccupantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccupationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OccupancyId");

                    b.HasIndex("OccupantId");

                    b.HasIndex("UnitId", "OccupantId")
                        .IsUnique();

                    b.ToTable("Occupancies");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationReference")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationId");

                    b.ToTable("CompanyTrusts");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Ownership", b =>
                {
                    b.Property<int>("OwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OwnershipId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("Ownerships", t =>
                        {
                            t.HasCheckConstraint("CK_Ownership_TypeOrganization", "(OwnershipType = 'Natural' AND OrganizationId IS NULL) OR (OwnershipType = 'Juristic' AND OrganizationId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.OwnershipContact", b =>
                {
                    b.Property<int>("OwnershipContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnershipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OwnershipContactId");

                    b.HasIndex("PersonId");

                    b.HasIndex("OwnershipId", "PersonId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.ParkingBay", b =>
                {
                    b.Property<int>("ParkingBayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNearEntrance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParkingBayNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParkingBayId");

                    b.HasIndex("UnitID");

                    b.HasIndex("PropertyId", "ParkingBayNumber")
                        .IsUnique();

                    b.ToTable("ParkingBays");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.StoreRoom", b =>
                {
                    b.Property<int>("StoreRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreRoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoreRoomId");

                    b.HasIndex("UnitId");

                    b.HasIndex("PropertyId", "StoreRoomNumber")
                        .IsUnique();

                    b.ToTable("StoreRooms");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.TagRemoteRecord", b =>
                {
                    b.Property<int>("TagRemoteRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RemotesAgent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RemotesOccupant")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RemotesOwner")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagsAgent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagsOccupant")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagRemoteRecordId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("TagRemoteRecords", t =>
                        {
                            t.HasCheckConstraint("CK_TagRemoteRecord_NonnegativeCounts", "(TagsOwner IS NULL OR TagsOwner >= 0) AND (RemotesOwner IS NULL OR RemotesOwner >= 0) AND (TagsOccupant IS NULL OR TagsOccupant >= 0) AND (RemotesOccupant IS NULL OR RemotesOccupant >= 0) AND (TagsAgent IS NULL OR TagsAgent >= 0) AND (RemotesAgent IS NULL OR RemotesAgent >= 0)");
                        });
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirconditioningUnits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DbInverter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Housekeeping")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnershipId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrimaryContactPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SublettingAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagRemoteRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("AgentId");

                    b.HasIndex("PrimaryContactPersonId");

                    b.HasIndex("BuildingId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.HasIndex("UnitId");

                    b.HasIndex("VehicleRegistration")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Agent", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.AgentCompany", "AgentCompany")
                        .WithMany("Agents")
                        .HasForeignKey("AgentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Person", "Person")
                        .WithOne("AgentProfile")
                        .HasForeignKey("BuildingRecordsApp.Models.Entities.Agent", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentCompany");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Building", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Property", "Property")
                        .WithMany("Buildings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Lease", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithOne("Lease")
                        .HasForeignKey("BuildingRecordsApp.Models.Entities.Lease", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Occupancy", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Person", "Occupant")
                        .WithMany("Occupancies")
                        .HasForeignKey("OccupantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithMany("Occupants")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occupant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Ownership", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Organization", "Organization")
                        .WithMany("Ownerships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithOne("Ownership")
                        .HasForeignKey("BuildingRecordsApp.Models.Entities.Ownership", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.OwnershipContact", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Ownership", "Ownership")
                        .WithMany("OwnershipContacts")
                        .HasForeignKey("OwnershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Person", "Person")
                        .WithMany("OwnershipContacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ownership");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.ParkingBay", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Property", "Property")
                        .WithMany("ParkingBays")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithMany("ParkingBays")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.StoreRoom", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Property", "Property")
                        .WithMany("StoreRooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithMany("StoreRooms")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.TagRemoteRecord", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithOne("TagRemoteRecord")
                        .HasForeignKey("BuildingRecordsApp.Models.Entities.TagRemoteRecord", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Unit", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Agent", "Agent")
                        .WithMany("Units")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildingRecordsApp.Models.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildingRecordsApp.Models.Entities.Person", "PrimaryContactPerson")
                        .WithMany("PrimaryContactUnits")
                        .HasForeignKey("PrimaryContactPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Building");

                    b.Navigation("PrimaryContactPerson");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Vehicle", b =>
                {
                    b.HasOne("BuildingRecordsApp.Models.Entities.Unit", "Unit")
                        .WithMany("Vehicles")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Agent", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.AgentCompany", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Building", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Organization", b =>
                {
                    b.Navigation("Ownerships");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Ownership", b =>
                {
                    b.Navigation("OwnershipContacts");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Person", b =>
                {
                    b.Navigation("AgentProfile");

                    b.Navigation("Occupancies");

                    b.Navigation("OwnershipContacts");

                    b.Navigation("PrimaryContactUnits");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Property", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("ParkingBays");

                    b.Navigation("StoreRooms");
                });

            modelBuilder.Entity("BuildingRecordsApp.Models.Entities.Unit", b =>
                {
                    b.Navigation("Lease");

                    b.Navigation("Occupants");

                    b.Navigation("Ownership");

                    b.Navigation("ParkingBays");

                    b.Navigation("StoreRooms");

                    b.Navigation("TagRemoteRecord");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
